crop_thresh: 0.6
visual: True
warmup_frame: 50


MOT:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_ppvehicle/
  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  skip_frame_num: 2 # preferably no more than 3
  enable: True

# VEHICLE_PLATE:
#   det_model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ch_PP-OCRv3_det_infer/
#   det_limit_side_len: 736
#   det_limit_type: "min"
#   rec_model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ch_PP-OCRv3_rec_infer/
#   rec_image_shape: [3, 48, 320]
#   rec_batch_num: 6
#   word_dict_path: deploy/pipeline/ppvehicle/rec_word_dict.txt
#   enable: True

VEHICLE_ATTR:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/vehicle_attribute_model/
  batch_size: 8
  color_threshold: 0.5
  type_threshold: 0.5
  enable: True

ATTR:
  model_dir:  https://bj.bcebos.com/v1/paddledet/models/pipeline/PPLCNet_x1_0_person_attribute_945_infer.zip
  batch_size: 8
  enable: True

